### ISSUE TITLE
Headless web version

### ISSUE THREAD

**Issue by dtrunk90** [giwty/nsp-update#101]
It would be great to have a web version to run it directly on a NAS for example

**Comment by Masamune3210** [comment]
the program already supports console operation, in fact, it originally didn't even have a GUI to begin with

**Comment by dtrunk90** [comment]
> the program already supports console operation, in fact, it originally didn't even have a GUI to begin with 

CLI != Web interface

**Comment by Masamune3210** [comment]
well considering the last commit was 2 years ago, It's probably safe to assume that your best chance is to pull the source and either get someone to add one for you or add it yourself

**Comment by dtrunk90** [comment]
It's in the making already since this project seems to be inactive
![Screenshot 2023-08-07 at 22-23-43 Library - Switch Library Manager Web](https://github.com/giwty/switch-library-manager/assets/636557/c209409b-8ec8-4df7-96f1-6054460868a6)
