### ISSUE TITLE
When entering DLC to ignore (language packs for example), settings.json resets and doesn't hold changes

### ISSUE THREAD

**Issue by ShadyMilkman42** [giwty/nsp-update#107]
Whenever I enter "ignore_dlc_title_ids": the settings.json file overwrites itself with several null and false commands and the Settings tab just shows:

{
  "folder": "E:\\Switch Games"
}

 What format is expected to accomplish this?

This is what I have for the bottom few rows

 "scan_recursively": false,
 "gui_page_size": 100,
 "ignore_dlc_title_ids": ["Hogwarts Legacy: Italian Language Pack [0100F7E00C70F00A]"
"Hogwarts Legacy: Portuguese (Brazil) Language Pack [0100F7E00C70F00C]"
"Hogwarts Legacy: Spanish (Mexico) Language Pack [0100F7E00C70F008]"
"Hogwarts Legacy: Japanese Language Pack [0100F7E00C70F00B]"
"Hogwarts Legacy: French Language Pack [0100F7E00C70F009]"
"Hogwarts Legacy: Spanish Language Pack [0100F7E00C70F007]"
"Hogwarts Legacy: German Language Pack [0100F7E00C70F006]"
]

**Comment by ASauvage** [comment]
Just put the title ID in quotes, not the full name. And in json you have to put a comma between the values. this means your ignored_dlc_title field should look like this:

```
"ignore_dlc_title_ids": [
  "0100F7E00C70F00A",
  "0100F7E00C70F00C",
  "0100F7E00C70F008",
  "0100F7E00C70F00B",
  "0100F7E00C70F009",
  "0100F7E00C70F007",
  "0100F7E00C70F006"
]
```

**Comment by ShadyMilkman42** [comment]
> Just put the title ID in quotes, not the full name. And in json you have to put a comma between the values. this means your ignored_dlc_title field should look like this:
> 
> ```
> "ignore_dlc_title_ids": [
>   "0100F7E00C70F00A",
>   "0100F7E00C70F00C",
>   "0100F7E00C70F008",
>   "0100F7E00C70F00B",
>   "0100F7E00C70F009",
>   "0100F7E00C70F007",
>   "0100F7E00C70F006"
> ]
> ```

That did it. Thank you! I had tried just the ID in quotes, but didn't include the comma, which made my settings revert back to default and erase any modifications I had done.
