### ISSUE TITLE
failed to read NSP [reason: non supported encryption type [encryption type:]

### ISSUE THREAD

**Issue by FrankEBailey** [giwty/nsp-update#66]
Hi, I'm not quite sure what to make of this error. One of the NSPs giving the issue is

TRIVIAL PURSUIT Live [010020700A5E0000] [v0].nsp

Let me know if you need me to upload it on mega or somewhere.

Thanks!

**Comment by giwty** [comment]
Just tried on my end with this file and had no issues.
Please verify your prod.keys file includes the latest firmware keys? (like key_area_key_application_0a).
If this still happens, please attach full log while on debug mode.

**Comment by giwty** [comment]
Closing, please reopen if this still happens
